### ISSUE TITLE
ui_preview.h file is missing

### ISSUE THREAD

**Issue by JavadHosseini** [adhitya1978/Erricson-dump-parser#1]
Hi,
I'm new to cpp,
there is an error in preview.cpp and is about ui_preview.h missing file,
would be so happy if you could help me with this.

**Comment by adhitya1978** [comment]
hi.let me check it out..Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Jey Hosseini <notifications@github.com> Date: 25/09/2020  21:49  (GMT+07:00) To: adhitya1978/Ericsson-dump-parser <Ericsson-dump-parser@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [adhitya1978/Ericsson-dump-parser] ui_preview.h file is missing (#1) 
Hi,
I'm new to cpp,
there is a error in preview.cpp and is about ui_preview.h missing file,
would be so happy if you could help me with this.

**Comment by adhitya1978** [comment]
Hi, Regarding ur mention its auto generated while u are imported to project build..before starting better to know how to build project using CMAKE/QMAKE also about tool chain likes MSVC/MINGW
previously code build using CMAKE and QTCreator as tools.
Regards
    Pada Senin, 28 September 2020 05.58.09 GMT+7, adhitya_1978 <adhitya_1978@ymail.com> menulis:  
 
 hi.let me check it out..



Sent from my Samsung Galaxy smartphone.

-------- Original message --------From: Jey Hosseini <notifications@github.com> Date: 25/09/2020 21:49 (GMT+07:00) To: adhitya1978/Ericsson-dump-parser <Ericsson-dump-parser@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [adhitya1978/Ericsson-dump-parser] ui_preview.h file is missing (#1) 



Hi,
I'm new to cpp,
there is a error in preview.cpp and is about ui_preview.h missing file,
would be so happy if you could help me with this.
